AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'test/test_helper.rb'
    - 'spec/mailers/previews/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'lib/tasks/**/*'
    - 'Rakefile'
    - 'Gemfile*'
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/EmptyMethod:
  EnforcedStyle: expanded

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

